#! /bin/sh

dunst &
exec $HOME/.config/picom/launch.sh &
sxhkd &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
exec $HOME/Documents/startserver.sh &
eww daemon &
exec $HOME/.config/eww/scripts/calendar.sh "$(date -d 'last month' +%-d.%-m.%+4Y)" &
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 10
feh --bg-fill ~/Pictures/ysmpiisha5a41.png
xset -dpms s off
xmodmap ~/.Xmodmap
owncloud &
exec $HOME/.config/eww/scripts/quotes.sh &

bspc config click_to_focus      button1
bspc config border_width        3
bspc config window_gap          10
bspc config swallow_first_click false
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_focus   false

bspc rule -a mpv state=pseudo_tiled
bspc rule -a Komikku state=pseudo_tiled
bspc rule -a Sxiv state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a scrcpy state=floating
bspc rule -a pomotroid state=pseudo_tiled

# Set the border colors.
bspc config normal_border_color "#44475a"
bspc config active_border_color "#44475a"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
